In [2]:
from dolfin import *
import numpy as np
np.set_printoptions(precision=3)

In [3]:
mesh = UnitIntervalMesh(3)
CG = FiniteElement('CG', mesh.ufl_cell(), 1)
W = FunctionSpace(mesh, CG * CG)
V = FunctionSpace(mesh, 'CG',1)

u1,u2 = TrialFunction(W)
v1,v2 = TestFunction(W)


Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [4]:
dx = Measure('dx', domain=mesh)
a11 = dot(grad(u1),grad(v1))*dx
a22 = dot(grad(u1),grad(v1))*dx
a = a11+a22
A = PETScMatrix()
assemble(a, tensor=A)
A = as_backend_type(A).mat()

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [5]:
A.getValues(range(mesh.num_vertices()*2), range(mesh.num_vertices()*2))

array([[ 6.,  0., -6.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-6.,  0., 12.,  0., -6.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -6.,  0., 12.,  0., -6.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -6.,  0.,  6.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
dofmap = W.dofmap()
for i, cell in enumerate(cells(mesh)):

    # Finding the dof's indices in the current cell
    indices = dofmap.cell_dofs(cell.index())
    #indices = np.sort(indices).astype(np.int32)
    print(indices)
    print(A.getValues(indices, indices))
    print(assemble_local(v1*dx+v2*dx,cell))
    print("\n")

[6 4 7 5]
[[ 6. -6.  0.  0.]
 [-6. 12.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Calling FFC just-in-time (JIT) compiler, this may take some time.
[0.167 0.167 0.167 0.167]


[4 2 5 3]
[[12. -6.  0.  0.]
 [-6. 12.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[0.167 0.167 0.167 0.167]


[2 0 3 1]
[[12. -6.  0.  0.]
 [-6.  6.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[0.167 0.167 0.167 0.167]




In [9]:
assemble(v1*dx)[:]

array([0.167, 0.   , 0.333, 0.   , 0.333, 0.   , 0.167, 0.   ])